runtime: nodejs18
env: standard

env_variables:
  NODE_ENV: production
  GOOGLE_CLOUD_PROJECT: "visa-rules-project"
  PORT: 8080

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 10

handlers:
  - url: /api/.*
    script: auto
    secure: always

  - url: /(.*\..*)$
    static_files: \1
    upload: (.*\..*)$

  - url: /.*
    static_files: index.html
    upload: index.html
